# Generated by Django 4.0 on 2024-11-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=200, verbose_name='Tên thành viên')),
                ('position', models.CharField(max_length=200, verbose_name='Vị trí')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='our_team_images/', verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name_plural': 'Thành viên đội (Team Members)',
            },
        ),
    ]
