# Generated by Django 4.0 on 2024-11-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_ourteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='facebook',
            field=models.URLField(default='exampleURL', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='instagram',
            field=models.URLField(default='exampleURL', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='twitter',
            field=models.URLField(default='exampleURL', verbose_name='Twitter'),
        ),
    ]
