# Generated by Django 4.0 on 2024-11-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_ourteam_email_ourteam_facebook_ourteam_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='facebook',
            field=models.URLField(verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='instagram',
            field=models.URLField(verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='twitter',
            field=models.URLField(verbose_name='Twitter'),
        ),
    ]
