# Generated by Django 4.0 on 2024-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_ourteam_email_alter_ourteam_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='facebook',
            field=models.URLField(null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='instagram',
            field=models.URLField(null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='twitter',
            field=models.URLField(null=True, verbose_name='Twitter'),
        ),
    ]
