# Generated by Django 4.0 on 2024-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_ourteam_facebook_remove_ourteam_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='social',
        ),
        migrations.AddField(
            model_name='ourteam',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
